const SS = SpreadsheetApp.getActiveSpreadsheet();
const SHEETS = {
  SP:'DM_SANPHAM', DVT:'SP_DONVITINH', NCC:'DM_NHACUNGCAP',
  PNHAP:'PN_PHIEUNHAP', CTNHAP:'PN_CHITIET',
  PBAN:'PB_PHIEUBAN', CTBAN:'PB_CHITIET',
  TONKHO:'TK_TONKHO', KHACH:'DM_KHACHHANG', CAIDAT:'CAIDAT',
  MASTER_DVT:'DM_DONVITINH', BACSI:'DM_BACSI', NHOMSP:'DM_NHOMSANPHAM',
  KKPHIEU:'KK_PHIEU', KKCHITIET:'KK_CHITIET',
  KTLPHIEU:'KTL_PHIEU', KTLCHITIET:'KTL_CHITIET',
  TNCCPHIEU:'TNCC_PHIEU', TNCCCHITIET:'TNCC_CHITIET',
  TCCN:'TCCN_PHIEU'
};

